### ISSUE TITLE
跑到本地，看不到小程序效果

### ISSUE THREAD

**Issue by bingely** [CoderMikeHe/flutter_wechat#5]

**Comment by CoderMikeHe** [comment]
安卓 还是 iOS??

**Comment by bingely** [comment]
安卓

**Comment by CoderMikeHe** [comment]
对对，因为我是 iOS 开发工程师，对Android 不懂，刚刚用 HUAWEI P30 真机调试了一下，确实存在这个问题。 但是 iOS 却是正常的，奇怪了。

**Comment by CoderMikeHe** [comment]
问题已经修复，代码已经提交，设置CustomScrollView 的 `physics: BouncingScrollPhysics()` 即可。
