### ISSUE TITLE
缺少_CupertinoAlertActionsRenderWidget

### ISSUE THREAD

**Issue by sinyscar** [CoderMikeHe/flutter_wechat#6]
本地编译保存，提示lib/components/action_sheet/action_sheet.dart:1026:7: Error: The non-abstract class '_ActionButtonParentDataWidget' is missing implementations for these members:
 - ParentDataWidget.debugTypicalAncestorWidgetClass

**Comment by CoderMikeHe** [comment]
能否提供一下Flutter版本号？我的是：Flutter：1.12.13 + Hotfix.7 。ib/components/action_sheet/action_sheet.dart  这个文件参照的是 CupertinoActionSheet  你可以参照一下。

**Comment by CoderMikeHe** [comment]
刚更新Flutter：1.12.13+hotfix.9，未见报错。是否你的版本过低导致。

**Comment by sinyscar** [comment]
我的版本号是Flutter 1.15.18 •

**Comment by wasdty** [comment]
在flutter版本1.17高版本下会出现_CupertinoAlertActionsRenderWidget

**Comment by CoderMikeHe** [comment]
好，可能是升级导致的，周末我更新一波 flutter sdk，然后修复一下。这两天手头上的事情比较多。

**Comment by CoderMikeHe** [comment]
已适配到 Flutter 1.17.1，修复了这个问题。

**Comment by wasdty** [comment]
👍
