### ISSUE TITLE
安卓启动页变形

### ISSUE THREAD

**Issue by DouSN** [CoderMikeHe/flutter_wechat#9]
请问安卓设备宽高比型号太多应该如何适配？ demo中用的18：9的图片在一些设备上拉伸了效果很差，如何解决这个问题？

**Comment by CoderMikeHe** [comment]
安卓 理论上提供几个常用规格的启动页，如果你是安卓开发，就按照你如何适配 原生安卓应用 启动页的一样即可。满足大多数即可

**Comment by DouSN** [comment]
@CoderMikeHe 感谢回复，还有一个ios和安卓都面临的问题：如果在flutter中使用闪屏页进行初始化操作，使用和启动页一样的图片，这样进入app后显示的图片（fit：Boxfit.cover）和启动页明显有区别，这种情况有解决方案吗？ 谢谢

**Comment by CoderMikeHe** [comment]
首先，闪屏页其实一般是非常快的，如果要做的非常精细，那得根据屏幕尺寸，加载不同尺寸的启动页作为闪屏页，fit：Boxfit.cover 这个属性可以尝试一下其他属性；其次，现实中，大部分闪屏页都是用来承接广告业务的；或者你去掉闪屏页中图片试试，看看效果。
